name: 'Setup MediaWiki Action'
author: Jeroen De Dauw
description: 'Downloads and installs MediaWiki into mediawiki/ so tests and CI can be run. Includes caching'

inputs:
  version:
    description: 'MediaWiki version. Needs to be available in git. Examples: master, REL1_35, 1.34.2'
    required: false
    default: 'REL1_35'
  extension:
    description: 'Name of MediaWiki extension to LOAD in LocalSettings. This action does not install the extension.'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Cache MediaWiki
      id: cache-mediawiki
      uses: actions/cache@v2
      with:
        path: |
          mediawiki
          !mediawiki/extensions/
          !mediawiki/vendor/
        key: mediawiki-cache

    - name: Cache Composer cache
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: composer-cache

    - name: Install MediaWiki
      if: steps.cache-mediawiki.outputs.cache-hit != 'true'
      working-directory: ~
      run: bash ${{ github.action_path }}/installMediaWiki.sh ${{ inputs.version }} ${{ inputs.extension }}
